/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "Riostream.h"

#include "PtDist.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include <math.h>
#include "TMath.h"

ClassImp(PtDist)


 PtDist::PtDist(const char *name, const char *title,
                        RooAbsReal& _x,
                        RooAbsReal& _p1,
                        RooAbsReal& _p2,
                        RooAbsReal& _p3) :
   RooAbsPdf(name,title),
   x("x","x",this,_x),
   p1("p1","p1",this,_p1),
   p2("p2","p2",this,_p2),
   p3("p3","p3",this,_p3)
 {
   cout<<"something"<<endl;
 }


 PtDist::PtDist(const PtDist& other, const char* name) :
   RooAbsPdf(other,name),
   x("x",this,other.x),
   p1("p1",this,other.p1),
   p2("p2",this,other.p2),
   p3("p3",this,other.p3)
 {
 }


 Double_t PtDist::evaluate() const
 {
   Double_t r = x/TMath::Power(1.+TMath::Power(x/p1,p2),p3);
   if(r>0) return r;
   else return r; 
 }
